# Created with YamlCreate.ps1 v2.2.0 using InputObject 🤖 $debug=QUSU.CRLF..7-2-10
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.2.0.schema.json

PackageIdentifier: tailscale.tailscale
PackageVersion: 1.40.0
InstallerLocale: en-US
MinimumOSVersion: 10.0.0.0
InstallerType: nullsoft
Scope: machine
InstallModes:
- interactive
- silent
UpgradeBehavior: install
ReleaseDate: 2023-04-26
Installers:
- Architecture: x86
  InstallerUrl: https://pkgs.tailscale.com/stable/tailscale-setup-1.40.0.exe
  InstallerSha256: 80646D6FA29C4EC02F868CE28A359FE6CEAB31D2C0192C70964AAB55E7F858D4
ManifestType: installer
ManifestVersion: 1.2.0
